# Site settings
title:       Kylie's Blog âœ¨
description: "Connecting dots... from Data to Destiny. ğŸ“ŠğŸ”®"
url:         https://SuperMoonChild.github.io
baseurl:     ""   # ğŸ‘ˆ è¿™ä¸€è¡Œä¿æŒä¸ºç©ºï¼Œéå¸¸é‡è¦

# Author
author:
  name:      Kylie
  email:     sophieli1231@gmail.com
  url:       https://SuperMoonChild.github.io

# Build settings
markdown:    kramdown

# Assets
sass:
  sass_dir:  _sass
  style:     compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate

# Permalinks
permalink:   /:year-:month-:day/:title
paginate:    5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email:     sophieli1231@gmail.com
  github:    https://github.com/SuperMoonChild
  linkedin:  https://www.linkedin.com/in/kaili8/
